version: "3.0"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/admin/.docker/config.json:/config.json
    command: --interval 30 --label-enable
    environment:
      - WATCHTOWER_LIFECYCLE_HOOKS=true
      - TZ=Asia/Irkutsk
      - WATCHTOWER_CLEANUP=true
  postgres:
    image: postgres:10
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:5432:5432'
  yoyo:
    image: docker.pkg.github.com/yoyofit/yoyo.fit/yoyo:latest
    env_file:
      - .env
    labels:
      com.centurylinklabs.watchtower.lifecycle.post-update: "update"
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - postgres
    volumes:
      - ./static:/srv/yoyo/static:z
      - ./media:/srv/yoyo/media:z
    ports:
      - 8000:8000
  caddy:
    image: lgatica/django-caddy:latest
    links:
      - yoyo:django
    environment:
      - PORT=8000
    ports:
      - 80:80
    volumes:
      - ./static:/var/www/static:z
      - ./media:/var/www/media:z
      - ./logs:/var/log:z
